# Generated by Django 4.2 on 2023-04-04 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=200)),
                ('tool', models.CharField(max_length=200)),
                ('fileName', models.CharField(max_length=200)),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('noOfPages', models.CharField(max_length=5)),
                ('fileOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookOwnerInfo', to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(related_name='fileInfosOfUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
